---
# bind9_simple_authoritative_dns_server/tasks/main.yml

- name: 'Install packages'
  import_tasks: install_packages.yml

- name: 'Configure bind9'
  import_tasks: configure_bind9.yml

- name: 'Start and enable the service'
  service:
    name: "{{ bind_systemd_unit }}"
    state: 'started'
    enabled: 'true'
